### ISSUE TITLE
Eliminate dependency on Bedtools

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#11]
We can estimate contig coverage via samtools and avoid introducing the need for bedtools.

**Comment by koadman** [comment]
not sure if you would get the same coverage estimates from samtools, quite likely they would be different.

**Comment by cerebis** [comment]
Its ok, really. None of the code to date is crucially dependent on this
quantity. I'll switch it over, no sense bringing in another binary for no
reason.

**Comment by cerebis** [comment]
Tried `samtools depth` but concerned that it is a little simplistic and there are discrepancies between these results and those from bedtools. I don't see how to easily generate depth statistics from mpileup.
