### ISSUE TITLE
lofreq appears to be missing.

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#17]
Haven't tested it but I don't see a binary for `lofreq`

Where I would like to maintain the directory structure.

```
external/
    lofreq/ -> lofreq_x.y.z/
    lofreq_x.y.z/
        lofreq
```

**Comment by cerebis** [comment]
Script is ready to accept the suggested path organisation.

**Comment by koadman** [comment]
whoopsie, this is all over on the multisample branch, will merge back into master again
