### ISSUE TITLE
phylogenetic tree generation

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#31]
It would be nice if you could generate trees within the pipeline. To that end, I have been prototyping a solution using the DendroPy module.

**Comment by koadman** [comment]
agree, this could be nice. BTW, BEAST is really really good at simulating trees from models ranging from simple birth/death or Yule processes to very complicated models. One way to do it is to specify the model you want in BEAUTi and give it an alignment that just has a single gap character for each sequence. Then when the resulting .xml is run with BEAST it will sample from the prior distribution, because gaps are treated as unknown data.

**Comment by cerebis** [comment]
I implemented something using DendroPy. Lacking a good understanding, I just chose the birth_death algorithm, but there were others.
- birth_death_tree
- discrete_birth_death_tree
- contained_coalescent_tree
- pure_kingman_tree
- mean_kingman_tree
- constrained_kingman_tree
- star_tree (trivial)

Any of them take your fancy? At least the B&D simulation doesn't require a sequence. I haven't looked into the others (would assume dB&D is similar though).

**Comment by cerebis** [comment]
http://dendropy.org/library/treesim.html

**Comment by koadman** [comment]
hard to beat the convenience of a python API call!
that collection of tree distributions should be plenty until we start getting into some really hard and focused questions

**Comment by koadman** [comment]
by hard and focused, i mean looking at things like population demographic histories with models like those in BEAST (e.g. skyline, skyride etc), where direct simulation from the prior may not be so easy. gah, 3am here. i should be sleeping.

**Comment by cerebis** [comment]
That's the sort of detailed requirement I too thought would be better deferred to when it was required. So long as the workflow supports the idea of tree generation then it shouldn't be difficult to substitute tools. 

Another recent publication:

Mallo, D., De Oliveira Martins, L., & Posada, D. (2016). SimPhy: Phylogenomic Simulation of Gene, Locus, and Species Trees. Syst Biol, 65(2), 334–344. http://doi.org/10.1093/sysbio/syv082

But I expect Beast is preferable being so well established.

**Comment by cerebis** [comment]
Reopening this until integrated in sweep. Integration overlaps significantly with issue #28

**Comment by cerebis** [comment]
I have added star generation commit: 5b653e3d14dc8f7ce0be57dd308d853f0afab6df. This should eliminate the need for explicit trees as files.
