### ISSUE TITLE
Non-deterministic cache misses

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#34]
Using -resume, some tasks that are completed successfully get repeated. Repeating this an second time will produce a different subset of repeats. 

Clearly something wrong in task caching.

**Comment by cerebis** [comment]
I've pinpointed this to the merging of sweep branches in the `joinChannels` function. There was a significant defect in joining, which would result in the loss of elements. Since order in the collections was not guaranteed between invocations, the lost elements were then random.

**Comment by cerebis** [comment]
This has been fixed in commit 39db05d0ec027bfc9c50e66e62d03c79e15d8227

**Comment by koadman** [comment]
just to confirm, this defect arises only when resuming, but not when a sweep is done in a single nextflow run?

**Comment by cerebis** [comment]
Currently this is a guess. I have not verified it on an actual run.
Debugging the system is challenging, even when you think you've whittled it
down.

With the current explanation, I expect it would have effected runs, in that
there would have been fewer final results than intended. That should have
stood out though and I did not notice it before finding the error.

Do you have results that you're worried about?
