### ISSUE TITLE
simForward.py appears to have a minor defect in sample from distributions

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#37]
When requesting read-pairs from various distributions, there is a small disagreement between what is requested and what is returned. As the number of pairs is increased, the discrepancy does not appear to diminish.

We need to check where this is coming from and remove it. Possibly this is 0 vs 1 based error or drawing values -- or similar.

**Comment by koadman** [comment]
I noticed this too, but didn't worry too much about it since being off-by-one in the read counts was no big deal for what I was doing. At least in my case it was due to rounding of fractional values.
