### ISSUE TITLE
SimForward must gracefully handle templates without cutsites

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#42]
SimForward expects to always find a cutsite on a target. This defect has persisted as templates up until now have always been very long and the cutters 4-cutters.

Mistakenly running this against a fragmented assembly has uncovered the error. An easy fix would be to just try again. However, this gives no surety. Instead, we should test all templates at the outset and only include those containing sites, or as we encounter non-containing templates, they should be marked off and no longer included in subsequent dice-rolls.

**Comment by koadman** [comment]
does the extreme situation of a chromosome/dataset having no target sites in any contig need special handling? Just report an error and quit?

**Comment by cerebis** [comment]
Yes, that's all that is going to happening actually. I just want it to be graceful, rather than just chuck an exception stack by blindly trying to normalise an empty matrix.
