### ISSUE TITLE
bash_configure not setting environment variables

### ISSUE THREAD

**Issue by koadman** [cerebis/meta-sweeper#57]
It looks like the configuration script isn't doing it's job on my ubuntu 16.04 machine:

```
koadman@oneida:~/git/meta-sweeper$ echo $NXF_CLASSPATH

koadman@oneida:~/git/meta-sweeper$ ./bash_configure 
Setting up meta-sweeper environment variables
Checking for nextflow: [OK]
Checking for BEAGLE_LIB: Warning: BEAGLE_LIB not set. At runtime BEAST needs to locate libhmsbeagle-jni.so
Inferring meta-sweeper installation directory to be: /home/koadman/git/meta-sweeper
Extending Nextflow class path: NXF_CLASSPATH += /home/koadman/git/meta-sweeper
koadman@oneida:~/git/meta-sweeper$ echo $NXF_CLASSPATH

koadman@oneida:~/git/meta-sweeper$ 
```

it's not obvious to me why this is failing.

**Comment by cerebis** [comment]
It doesn't look like you set BEAGLE_LIB prior to sourcing bash_configure.

It should point to the directory containing the .so library.

Eg.

export BEAGLE_LIB=/usr/lib64

The script doesn't try to find the library itself. I can make it look in
standard places, but for now this is left as the responsibility of the user.

**Comment by cerebis** [comment]
Also, per the documentation, this is a script that must be sourced rather than executed. Executed scripts will not export changed environmental variables to the current user shell.

**Comment by koadman** [comment]
yup, i missed the detail of sourcing vs. executing. looks good.
