### ISSUE TITLE
params.debug undefined

### ISSUE THREAD

**Issue by koadman** [cerebis/meta-sweeper#61]
The 3C and timeseries workflow use a variable called params.debug which is undefined. This causes nextflow to abort immediately. Adding:
```
params.debug=false
```
near the top of the workflow resolves the issue

**Comment by cerebis** [comment]
Meta-sweeper is only tested with Nextflow up to 0.19. I strongly suspect this is caused by changes within Nextflow, since previously the variable debug was set to false by default.

**Comment by koadman** [comment]
yes, on 0.22.5

**Comment by cerebis** [comment]
I've not reproduced this error yet, but we can move this declaration to nextflow.config.

**Comment by cerebis** [comment]
I've added this to ts-multi, if you can get a chance to test it in your environment.

**Comment by cerebis** [comment]
Master closes by 4f415d146d5e167fd28a078e7eb7f0432df4b0f0
Previously addressed on ts-multi
