### ISSUE TITLE
A5 use of Unix "file" command is tricked by symbolic links

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#79]
When A5 is supplied compressed reads as input, it will auto-magically determine that the files are compressed. It does this by use of the Unix command, ie ```file $file```. For a symbolic link however, the result will only report that it is a link, not that the referred to file is compressed.

I have changed A5 to deference symlinks as ```file -L $file```, so that the type of the real file is reported instead.

**Comment by koadman** [comment]
good find! I will make a note to fix this in the A5 code repo as well

**Comment by cerebis** [comment]
Great. I wasn't sure whether to post it on SF.
