### ISSUE TITLE
Nextflow breaks on PBSPro because of script names.

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#9]
Related to #8 

Nextflow attempts to be unobtrusive by hiding its execution related cruft using the hidden file name convention.

Eg. `.command.xxx`

In PBSPro job names are initially inherited from the script name in all cases, unless the name is given on the command line itself with -N. Eg `qsub -N jobname ...`. 

Even in cases where the job name is specified within the script with the directive `#PBS -N jobname`, there is a momentary period when the job inherits the script filename prior to taking on the name parsed from within it. 

In PBSPro, job names must begin with an alphanumeric character. Since Nextflow has chosen to hide its scripts, the first character is then `.` and the job submission is refused immediately.

There does not appear to be a facility for overriding these names in Nextflow. This would possibly be a solution. What real value is there in hiding this detail anyhow?

**Further**

PBSPro job names have a strict maximum length. As processes are named after the workflow names, along with some additional details, these can exceed the limit. A check has to be applied.

**Comment by cerebis** [comment]
I have hacked this quickly by deleting the leading `.` on all execution commands. Jobs appear to submit fine in this situation.

**Comment by koadman** [comment]
can this be pushed upstream to the nextflow guys?

**Comment by cerebis** [comment]
That's the idea once I make a tidier fix. Right now, I've just overridden
the standard PBS executor which was probably working fine on Torque.

**Comment by cerebis** [comment]
I've forked [Nextflow (0.19.xx)](https://github.com/cerebis/nextflow) implemented explicit support for PBSPro.
